name: di

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  data:
    path: ../data  
  domain:
    path: ../domain

  get_it: ^4.0.4  
  
  cloud_firestore: ^0.14.0+2