name: personal_finances
description: Personal project to test Clean Architecture structure.

version: 1.1.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #core  
  presentation_core:
    path: ../../core/presentation_core

  application:
    path: ../application
  domain:
    path: ../domain
  di:
    path: ../di

flutter:
  uses-material-design: true