name: personal_finances
description: An example of Clean Architecture.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  presentation:
    path: ../presentation 

flutter:
  uses-material-design: true